/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AppRepasoRouteImport } from './routes/_app/repaso'
import { Route as AppLeaderboardRouteImport } from './routes/_app/leaderboard'
import { Route as AppMeIndexRouteImport } from './routes/_app/me/index'
import { Route as AppCoursesIndexRouteImport } from './routes/_app/courses/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppMeSettingsRouteImport } from './routes/_app/me/settings'
import { Route as AppCoursesModuleSlugCompleteRouteImport } from './routes/_app/courses/$moduleSlug/complete'
import { Route as AppCoursesModuleSlugLessonLessonIdRouteImport } from './routes/_app/courses/$moduleSlug/lesson.$lessonId'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AppRepasoRoute = AppRepasoRouteImport.update({
  id: '/repaso',
  path: '/repaso',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMeIndexRoute = AppMeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMeSettingsRoute = AppMeSettingsRouteImport.update({
  id: '/me/settings',
  path: '/me/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesModuleSlugCompleteRoute =
  AppCoursesModuleSlugCompleteRouteImport.update({
    id: '/courses/$moduleSlug/complete',
    path: '/courses/$moduleSlug/complete',
    getParentRoute: () => AppRoute,
  } as any)
const AppCoursesModuleSlugLessonLessonIdRoute =
  AppCoursesModuleSlugLessonLessonIdRouteImport.update({
    id: '/courses/$moduleSlug/lesson/$lessonId',
    path: '/courses/$moduleSlug/lesson/$lessonId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/repaso': typeof AppRepasoRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/me/settings': typeof AppMeSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/courses/': typeof AppCoursesIndexRoute
  '/me/': typeof AppMeIndexRoute
  '/courses/$moduleSlug/complete': typeof AppCoursesModuleSlugCompleteRoute
  '/courses/$moduleSlug/lesson/$lessonId': typeof AppCoursesModuleSlugLessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/repaso': typeof AppRepasoRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/me/settings': typeof AppMeSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/courses': typeof AppCoursesIndexRoute
  '/me': typeof AppMeIndexRoute
  '/courses/$moduleSlug/complete': typeof AppCoursesModuleSlugCompleteRoute
  '/courses/$moduleSlug/lesson/$lessonId': typeof AppCoursesModuleSlugLessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/repaso': typeof AppRepasoRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_app/me/settings': typeof AppMeSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/courses/': typeof AppCoursesIndexRoute
  '/_app/me/': typeof AppMeIndexRoute
  '/_app/courses/$moduleSlug/complete': typeof AppCoursesModuleSlugCompleteRoute
  '/_app/courses/$moduleSlug/lesson/$lessonId': typeof AppCoursesModuleSlugLessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/repaso'
    | '/signin'
    | '/signup'
    | '/me/settings'
    | '/api/auth/$'
    | '/courses/'
    | '/me/'
    | '/courses/$moduleSlug/complete'
    | '/courses/$moduleSlug/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/repaso'
    | '/signin'
    | '/signup'
    | '/me/settings'
    | '/api/auth/$'
    | '/courses'
    | '/me'
    | '/courses/$moduleSlug/complete'
    | '/courses/$moduleSlug/lesson/$lessonId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_marketing'
    | '/_app/leaderboard'
    | '/_app/repaso'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_marketing/'
    | '/_app/me/settings'
    | '/api/auth/$'
    | '/_app/courses/'
    | '/_app/me/'
    | '/_app/courses/$moduleSlug/complete'
    | '/_app/courses/$moduleSlug/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/repaso': {
      id: '/_app/repaso'
      path: '/repaso'
      fullPath: '/repaso'
      preLoaderRoute: typeof AppRepasoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me/': {
      id: '/_app/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof AppMeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/': {
      id: '/_app/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/me/settings': {
      id: '/_app/me/settings'
      path: '/me/settings'
      fullPath: '/me/settings'
      preLoaderRoute: typeof AppMeSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/$moduleSlug/complete': {
      id: '/_app/courses/$moduleSlug/complete'
      path: '/courses/$moduleSlug/complete'
      fullPath: '/courses/$moduleSlug/complete'
      preLoaderRoute: typeof AppCoursesModuleSlugCompleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/$moduleSlug/lesson/$lessonId': {
      id: '/_app/courses/$moduleSlug/lesson/$lessonId'
      path: '/courses/$moduleSlug/lesson/$lessonId'
      fullPath: '/courses/$moduleSlug/lesson/$lessonId'
      preLoaderRoute: typeof AppCoursesModuleSlugLessonLessonIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppRepasoRoute: typeof AppRepasoRoute
  AppMeSettingsRoute: typeof AppMeSettingsRoute
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
  AppMeIndexRoute: typeof AppMeIndexRoute
  AppCoursesModuleSlugCompleteRoute: typeof AppCoursesModuleSlugCompleteRoute
  AppCoursesModuleSlugLessonLessonIdRoute: typeof AppCoursesModuleSlugLessonLessonIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppRepasoRoute: AppRepasoRoute,
  AppMeSettingsRoute: AppMeSettingsRoute,
  AppCoursesIndexRoute: AppCoursesIndexRoute,
  AppMeIndexRoute: AppMeIndexRoute,
  AppCoursesModuleSlugCompleteRoute: AppCoursesModuleSlugCompleteRoute,
  AppCoursesModuleSlugLessonLessonIdRoute:
    AppCoursesModuleSlugLessonLessonIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MarketingRouteChildren {
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
